packages:
  - packages/*
  - contracts/*

catalog:
  ethers: ^6.16.0
  typescript: ^5.9.3
  dotenv: ^17.2.3

catalogs:
  hardhat2:
    hardhat: 2.28.2
    "@nomicfoundation/hardhat-toolbox": ^6.1.2
    "@nomicfoundation/hardhat-ethers": ^3.1.3
    "@nomicfoundation/hardhat-network-helpers": ^1.1.2
    "@openzeppelin/hardhat-upgrades": ^3.9.1
    hardhat-contract-sizer: ^2.10.1
    hardhat-gas-reporter: ^1.0.8
    chai: ^4.2.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - keccak
  - secp256k1

overrides:
  cookie@<0.7.0: ">=0.7.0"
  qs@<6.14.1: ">=6.14.1"
  tmp@<=0.2.3: ">=0.2.4"

publicHoistPattern: []
