packages:
  - packages/*
  - contracts/*

catalog:
  '@openzeppelin/contracts': 5.5.0
  '@openzeppelin/contracts-upgradeable': 5.5.0
  dotenv: ^17.2.3
  ethers: ^6.16.0
  typescript: ^5.9.3

catalogs:
  hardhat2:
    '@nomicfoundation/hardhat-chai-matchers': ^2.1.0
    '@nomicfoundation/hardhat-ethers': ^3.1.3
    '@nomicfoundation/hardhat-network-helpers': ^1.1.2
    '@nomicfoundation/hardhat-toolbox': ^6.1.2
    '@openzeppelin/hardhat-upgrades': ^3.9.1
    chai: ^4.2.0
    hardhat: 2.28.3
    hardhat-contract-sizer: ^2.10.1
    hardhat-gas-reporter: ^1.0.8

linkWorkspacePackages: true

onlyBuiltDependencies:
  - keccak
  - secp256k1

overrides:
  cookie@<0.7.0: '>=0.7.0'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  tmp@<=0.2.3: '>=0.2.4'
#  undici@<6.23.0: '>=6.23.0' we cant override it because hardhat 2 uses it and cant work with overrides

publicHoistPattern: []
